### ISSUE TITLE
Bug with stylelint --fix

### ISSUE THREAD

**Issue by lordprotein** [hudochenkov/postcss-styled-syntax#4] opened 2023-01-12 11:08 UTC
![image](https://user-images.githubusercontent.com/39030827/212050393-cd553c51-f068-49f7-b9c7-81b5037df5a1.png)

I'm trying to use it, but I'm getting an error

Versions: 
 "styled-components": "^5.3.3"
 "postcss-styled-syntax": "^0.3.1"

<img width="379" alt="image" src="https://user-images.githubusercontent.com/39030827/212050918-d51b86a2-f485-4749-919d-dea1cbbf83d5.png">
.stylelintrc

**Comment by hudochenkov** [comment] 2023-01-12 15:56
Could you share file content (only minimal content that needs to trigger issue) that trigger this issue?

What is stylelint version? What is your Node.js version?

Could you also share output of these two commands to see what versions are in node_modules?

```bash
npm ls postcss
```

```bash
npm ls stylelint
```

**Comment by lordprotein** [comment] 2023-01-13 10:34
Node: v16.16.0
The problem causes absolutely all files with the extension ts, tsx, jsx

```├─┬ @stylelint/postcss-css-in-js@0.38.0
│ └── postcss@7.0.39 invalid: "^8.4.21" from node_modules/postcss-styled-syntax
├─┬ postcss-styled-syntax@0.3.1
│ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
├─┬ razzle-plugin-purgecss@1.0.1
│ └─┬ purgecss-webpack-plugin@1.6.0
│   └─┬ purgecss@1.4.2
│     └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
├─┬ razzle@4.2.17
│ ├─┬ autoprefixer@10.4.12
│ │ └── postcss@8.4.17 deduped
│ ├─┬ css-loader@5.2.7
│ │ ├─┬ icss-utils@5.1.0
│ │ │ └── postcss@8.4.17 deduped
│ │ ├─┬ postcss-modules-extract-imports@3.0.0
│ │ │ └── postcss@8.4.17 deduped
│ │ ├─┬ postcss-modules-local-by-default@4.0.0
│ │ │ └── postcss@8.4.17 deduped
│ │ ├─┬ postcss-modules-scope@3.0.0
│ │ │ └── postcss@8.4.17 deduped
│ │ ├─┬ postcss-modules-values@4.0.0
│ │ │ └── postcss@8.4.17 deduped
│ │ └── postcss@8.4.17
│ ├─┬ css-minimizer-webpack-plugin@1.3.0
│ │ └─┬ cssnano@4.1.11
│ │   ├─┬ cssnano-preset-default@4.0.8
│ │   │ ├─┬ css-declaration-sorter@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ cssnano-util-raw-cache@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-calc@7.0.5
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-colormin@4.0.3
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-convert-values@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-discard-comments@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-discard-duplicates@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-discard-empty@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-discard-overridden@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-merge-longhand@4.0.11
│ │   │ │ ├── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ │ └─┬ stylehacks@4.0.3
│ │   │ │   └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-merge-rules@4.0.3
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-minify-font-values@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-minify-gradients@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-minify-params@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-minify-selectors@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-charset@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-display-values@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-positions@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-repeat-style@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-string@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-timing-functions@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-unicode@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-url@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-normalize-whitespace@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-ordered-values@4.1.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-reduce-initial@4.0.3
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-reduce-transforms@4.0.2
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-svgo@4.0.3
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ ├─┬ postcss-unique-selectors@4.0.1
│ │   │ │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   │ └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ │   └── postcss@7.0.39 deduped invalid: "^8.4.21" from node_modules/postcss-styled-syntax
│ ├─┬ postcss-load-config@3.1.4
│ │ └── postcss@8.4.17 deduped
│ ├─┬ postcss-loader@4.3.0
│ │ └── postcss@8.4.17 deduped
│ └── postcss@8.4.17
└─┬ stylelint@14.16.1
  ├─┬ @csstools/selector-specificity@2.0.2
  │ └── postcss@8.4.21 deduped
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.4.21 deduped
  └── postcss@8.4.21

npm ERR! code ELSPROBLEMS
npm ERR! invalid: postcss@7.0.39 
```

```
├─┬ stylelint-config-recommended@9.0.0
│ └── stylelint@14.16.1 deduped
└── stylelint@14.16.1
```

**Comment by hudochenkov** [comment] 2023-01-13 11:58
I see that there are different PostCSS versions in your tools. And for some reason wrong PostCSS version (7.0.39) is forced to be used with `postcss-styled-syntax`. While Stylelint has newer version `8.4.21`.

This is not a problem with Stylelint or `postcss-styled-syntax`. But with your specific install.

To fix your install this might help.

1. Uninstall `@stylelint/postcss-css-in-js`.

2. Uninstall and install again packages, that use PostCSS:

```
postcss-styled-syntax
razzle-plugin-purgecss
razzle
stylelint
```

3. Check with `npm ls postcss` that there are no `deduped invalid` messages and no errors at the end. All PostCSS versions should be 8.4.21.

**Comment by lordprotein** [comment] 2023-01-13 12:28
Some packages of Razzle (css-minimizer-webpack-plugin@1.3.0) are still installed with postcss@7.0.39 and have not been updated to the latest(
I updated package css-minimizer-webpack-plugin to v4.2.2 manually, but the error did not disappear

```├─┬ autoprefixer@10.4.13
│ └── postcss@8.4.21 deduped
├─┬ css-loader@5.2.7
│ ├─┬ icss-utils@5.1.0
│ │ └── postcss@8.4.21 deduped
│ ├─┬ postcss-modules-extract-imports@3.0.0
│ │ └── postcss@8.4.21 deduped
│ ├─┬ postcss-modules-local-by-default@4.0.0
│ │ └── postcss@8.4.21 deduped
│ ├─┬ postcss-modules-scope@3.0.0
│ │ └── postcss@8.4.21 deduped
│ ├─┬ postcss-modules-values@4.0.0
│ │ └── postcss@8.4.21 deduped
│ └── postcss@8.4.21 deduped
├─┬ css-minimizer-webpack-plugin@4.2.2
│ ├─┬ cssnano@5.1.14
│ │ ├─┬ cssnano-preset-default@5.2.13
│ │ │ ├─┬ css-declaration-sorter@6.3.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ cssnano-utils@3.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-calc@8.2.4
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-colormin@5.3.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-convert-values@5.1.3
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-discard-comments@5.1.2
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-discard-duplicates@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-discard-empty@5.1.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-discard-overridden@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-merge-longhand@5.1.7
│ │ │ │ ├── postcss@8.4.21 deduped
│ │ │ │ └─┬ stylehacks@5.1.1
│ │ │ │   └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-merge-rules@5.1.3
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-minify-font-values@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-minify-gradients@5.1.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-minify-params@5.1.4
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-minify-selectors@5.2.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-charset@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-display-values@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-positions@5.1.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-repeat-style@5.1.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-string@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-timing-functions@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-unicode@5.1.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-url@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-normalize-whitespace@5.1.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-ordered-values@5.1.3
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-reduce-initial@5.1.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-reduce-transforms@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-svgo@5.1.0
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ ├─┬ postcss-unique-selectors@5.1.1
│ │ │ │ └── postcss@8.4.21 deduped
│ │ │ └── postcss@8.4.21 deduped
│ │ └── postcss@8.4.21 deduped
│ └── postcss@8.4.21 deduped
├─┬ postcss-load-config@3.1.4
│ └── postcss@8.4.21 deduped
├─┬ postcss-loader@4.3.0
│ └── postcss@8.4.21 deduped
└── postcss@8.4.21```

**Comment by hudochenkov** [comment] 2023-01-13 13:42
I don't see Stylelint or `postcss-styled-syntax` in this output.

---

When I try to install these packages:

```
npm i postcss-styled-syntax razzle-plugin-purgecss razzle stylelint
```

PostCSS version is correct for Stylelint and `postcss-styled-syntax`:

```
├─┬ postcss-styled-syntax@0.3.1
│ └── postcss@8.4.21
├─┬ razzle-plugin-purgecss@1.0.1
│ └─┬ purgecss-webpack-plugin@1.6.0
│   └─┬ purgecss@1.4.2
│     └── postcss@7.0.39
├─┬ razzle@4.2.18
│ ├─┬ autoprefixer@10.4.13
│ │ └── postcss@8.4.21 deduped
│ ├─┬ css-loader@5.2.7
│ │ ├─┬ icss-utils@5.1.0
│ │ │ └── postcss@8.4.21 deduped
│ │ ├─┬ postcss-modules-extract-imports@3.0.0
│ │ │ └── postcss@8.4.21 deduped
│ │ ├─┬ postcss-modules-local-by-default@4.0.0
│ │ │ └── postcss@8.4.21 deduped
│ │ ├─┬ postcss-modules-scope@3.0.0
│ │ │ └── postcss@8.4.21 deduped
│ │ ├─┬ postcss-modules-values@4.0.0
│ │ │ └── postcss@8.4.21 deduped
│ │ └── postcss@8.4.21 deduped
│ ├─┬ css-minimizer-webpack-plugin@1.3.0
│ │ └─┬ cssnano@4.1.11
│ │   ├─┬ cssnano-preset-default@4.0.8
│ │   │ ├─┬ css-declaration-sorter@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ cssnano-util-raw-cache@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-calc@7.0.5
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-colormin@4.0.3
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-convert-values@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-discard-comments@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-discard-duplicates@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-discard-empty@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-discard-overridden@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-merge-longhand@4.0.11
│ │   │ │ ├── postcss@7.0.39
│ │   │ │ └─┬ stylehacks@4.0.3
│ │   │ │   └── postcss@7.0.39
│ │   │ ├─┬ postcss-merge-rules@4.0.3
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-minify-font-values@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-minify-gradients@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-minify-params@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-minify-selectors@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-charset@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-display-values@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-positions@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-repeat-style@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-string@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-timing-functions@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-unicode@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-url@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-whitespace@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-ordered-values@4.1.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-reduce-initial@4.0.3
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-reduce-transforms@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-svgo@4.0.3
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-unique-selectors@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ └── postcss@7.0.39
│ │   └── postcss@7.0.39
│ ├─┬ postcss-load-config@3.1.4
│ │ └── postcss@8.4.21 deduped
│ ├─┬ postcss-loader@4.3.0
│ │ └── postcss@8.4.21 deduped
│ └── postcss@8.4.21 deduped
└─┬ stylelint@14.16.1
  ├─┬ @csstools/selector-specificity@2.0.2
  │ └── postcss@8.4.21 deduped
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.4.21 deduped
  └── postcss@8.4.21 deduped
```

P. S. Use three backticks, instead one when posting output. Then Github shows it correctly.

<pre><code>
```
```
</code></pre>

**Comment by lordprotein** [comment] 2023-01-16 11:38
Found a problem related to different versions. The fact is that the postcss itself was not installed
Now I don't have version conflicts and I get this error and I still can't figure out why
<img width="470" alt="image" src="https://user-images.githubusercontent.com/39030827/212669406-282554de-7618-464a-afb9-41e2fcb5801f.png">

```
├─┬ postcss-jsx@0.36.4
│ └── postcss@8.4.21 deduped
├─┬ postcss-styled-syntax@0.3.1
│ └── postcss@8.4.21 deduped
├─┬ postcss-syntax@0.36.2
│ └── postcss@8.4.21 deduped
├── postcss@8.4.21
├─┬ razzle-plugin-purgecss@1.0.1
│ └─┬ purgecss-webpack-plugin@1.6.0
│   └─┬ purgecss@1.4.2
│     └── postcss@7.0.39
├─┬ razzle@4.2.18
│ ├─┬ autoprefixer@10.4.13
│ │ └── postcss@8.4.21 deduped
│ ├─┬ css-loader@5.2.7
│ │ ├─┬ icss-utils@5.1.0
│ │ │ └── postcss@8.4.21 deduped
│ │ ├─┬ postcss-modules-extract-imports@3.0.0
│ │ │ └── postcss@8.4.21 deduped
│ │ ├─┬ postcss-modules-local-by-default@4.0.0
│ │ │ └── postcss@8.4.21 deduped
│ │ ├─┬ postcss-modules-scope@3.0.0
│ │ │ └── postcss@8.4.21 deduped
│ │ ├─┬ postcss-modules-values@4.0.0
│ │ │ └── postcss@8.4.21 deduped
│ │ └── postcss@8.4.21 deduped
│ ├─┬ css-minimizer-webpack-plugin@1.3.0
│ │ └─┬ cssnano@4.1.11
│ │   ├─┬ cssnano-preset-default@4.0.8
│ │   │ ├─┬ css-declaration-sorter@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ cssnano-util-raw-cache@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-calc@7.0.5
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-colormin@4.0.3
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-convert-values@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-discard-comments@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-discard-duplicates@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-discard-empty@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-discard-overridden@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-merge-longhand@4.0.11
│ │   │ │ ├── postcss@7.0.39
│ │   │ │ └─┬ stylehacks@4.0.3
│ │   │ │   └── postcss@7.0.39
│ │   │ ├─┬ postcss-merge-rules@4.0.3
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-minify-font-values@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-minify-gradients@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-minify-params@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-minify-selectors@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-charset@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-display-values@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-positions@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-repeat-style@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-string@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-timing-functions@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-unicode@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-url@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-normalize-whitespace@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-ordered-values@4.1.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-reduce-initial@4.0.3
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-reduce-transforms@4.0.2
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-svgo@4.0.3
│ │   │ │ └── postcss@7.0.39
│ │   │ ├─┬ postcss-unique-selectors@4.0.1
│ │   │ │ └── postcss@7.0.39
│ │   │ └── postcss@7.0.39
│ │   └── postcss@7.0.39
│ ├─┬ postcss-load-config@3.1.4
│ │ └── postcss@8.4.21 deduped
│ ├─┬ postcss-loader@4.3.0
│ │ └── postcss@8.4.21 deduped
│ └── postcss@8.4.21 deduped
├─┬ stylelint-processor-styled-components@1.10.0
│ └── postcss@7.0.39
└─┬ stylelint@14.16.1
  ├─┬ @csstools/selector-specificity@2.0.2
  │ └── postcss@8.4.21 deduped
  ├─┬ postcss-safe-parser@6.0.0
  │ └── postcss@8.4.21 deduped
  └── postcss@8.4.21 deduped

```

```
├─┬ stylelint-config-recommended@7.0.0
│ └── stylelint@14.16.1 deduped
└── stylelint@14.16.1

```

**Comment by hudochenkov** [comment] 2023-01-16 11:47
What is the content of a file that it can't parse? Could you find what part of it causes an issue and share?

**Comment by lordprotein** [comment] 2023-01-16 11:52
Sure
The error occurs absolutely in all files that contain Styled
As template:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/39030827/212672051-379ceb1d-ce12-4370-a5b5-e99860cabf1d.png">

**Comment by hudochenkov** [comment] 2023-01-16 11:55
Could you create a repository with reproduced error? I can't understand what is happening. Everything seems in order. Make sure to include `tsconfig.json` if you have it in the repository as it might or might not have an impact.

**Comment by qeleb** [comment] 2023-02-09 00:31
+1 having this same issue

**Comment by hudochenkov** [comment] 2023-02-09 00:57
@qeleb Could you create a repository with reproduced error?

**Comment by qeleb** [comment] 2023-02-09 01:56
@hudochenkov Hi! No worries. I’ve sorted out my problem somehow over the past hour and a half of troubleshooting.
I was switching between your `postcss-styled-syntax` and `postcss-lit` and actually having the same issue with both. Ultimately I fixed it somehow and landed on a working solution with `postcss-lit`.

After all of that trouble, I can finally use your css property ordering— I love it. Thanks for making it and for the quick reply :)

**Comment by hudochenkov** [comment] 2023-02-26 21:48
Closing as there is no follow up.

**Closed as completed by hudochenkov** 2023-02-26 21:48 UTC
